# Generated by Django 3.2.6 on 2021-12-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishmaker',
            new_name='wishmaster',
        ),
    ]
