# Generated by Django 3.2.6 on 2021-12-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='openning_hour',
            new_name='opening_hour',
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
